add_subdirectory(Mocks)
add_subdirectory(BrokerLock)
if(TARGET_SAMV71Q21)
    add_subdirectory(SamV71Core)
endif()
if(TARGET_SAMRH71F20)
    add_subdirectory(SamRH71Core)
endif()
add_subdirectory(Hal)
add_subdirectory(Monitor)
add_subdirectory(ThreadsCommon)
if(TARGET_SAMV71Q21)
    add_subdirectory(Xdmac)
endif()
add_subdirectory(FaultHandler)
add_subdirectory(BootHelper)
