name: Workflow

on: [pull_request]

permissions:
  contents: read

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        # Checkout submodules too (recursively) so tests and build can access them
        submodules: 'recursive'
    - name: Install dependencies
      run: |
        sudo apt update && sudo apt install -y build-essential cppcheck cmake clang-format curl ninja-build
    - name: Install taste-rtems-qdp-arm
      run: |
        curl -s -L https://github.com/n7space/TASTE-RTEMS-QDP-ARM/releases/download/v1.1.0/taste-rtems-qdp-arm.tar.xz | tar -Jxf - -C /opt
        echo "/opt/taste-rtems-qdp-arm/bin" >> $GITHUB_PATH
    - name: Check code formatting
      run: |
        ./clang-format-check.sh check
    - name: Build SamV71Q21
      run: |
        mkdir build-samv
        cmake -S . -B build-samv -G Ninja -DCMAKE_BUILD_TYPE=Debug -DTARGET_SAMV71Q21=ON -DTOOLS_ENABLE_CPPCHECK=ON
        cmake --build build-samv
    - name: BuildSamRH71F20
      run: |
        mkdir build-samrh
        cmake -S . -B build-samrh -G Ninja -DCMAKE_BUILD_TYPE=Debug -DTARGET_SAMRH71F20=ON -DTOOLS_ENABLE_CPPCHECK=ON
        cmake --build build-samrh
    - name: Functional check
      run: make -C test test
